import {ApplicationConfig, provideBrowserGlobalErrorListeners} from '@angular/core';
import {provideRouter} from '@angular/router';
import {provideAnimationsAsync} from '@angular/platform-browser/animations/async';
import {provideHttpClient, withInterceptors} from '@angular/common/http';
import {providePrimeNG} from 'primeng/config';
import Aura from '@primeuix/themes/aura';

import {routes} from './app.routes';
import {provideClientHydration} from '@angular/platform-browser';
import {errorInterceptor} from './core/interceptors/error.interceptor';
import {loadingInterceptor} from './core/interceptors/loading.interceptor';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideRouter(routes),
    provideClientHydration(),
    provideAnimationsAsync(),
    provideHttpClient(withInterceptors([errorInterceptor, loadingInterceptor])),
    providePrimeNG({
      ripple: true,
      inputVariant: 'filled',
      translation: {
        accept: 'Aceitar',
        reject: 'Rejeitar',
        cancel: 'Cancelar',
        completed: 'Concluido',
        pending: 'Pendente',
        dayNames: [
          'Domingo',
          'Segunda-feira',
          'Terca-feira',
          'Quarta-feira',
          'Quinta-feira',
          'Sexta-feira',
          'Sabado',
        ],
        dayNamesShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab'],
        dayNamesMin: ['Do', 'Se', 'Te', 'Qa', 'Qi', 'Se', 'Sa'],
        monthNames: [
          'Janeiro',
          'Fevereiro',
          'Marco',
          'Abril',
          'Maio',
          'Junho',
          'Julho',
          'Agosto',
          'Setembro',
          'Outubro',
          'Novembro',
          'Dezembro',
        ],
        monthNamesShort: [
          'Jan',
          'Fev',
          'Mar',
          'Abr',
          'Mai',
          'Jun',
          'Jul',
          'Ago',
          'Set',
          'Out',
          'Nov',
          'Dez',
        ],
        choose: 'Escolher',
        upload: 'Enviar',
        clear: 'Limpar',
        searchMessage: '{0} resultados disponiveis',
        today: 'Hoje',
        noFilter: 'Sem filtro',
        addRule: 'Adicionar regra',
        removeRule: 'Remover regra',
        matchAll: 'Coincidir todos',
        emptyMessage: 'Nenhum resultado encontrado',
        emptyFilterMessage: 'Nenhum resultado encontrado',
        emptySelectionMessage: 'Nenhuma selecao',
        emptySearchMessage: 'Nenhum resultado encontrado',
        gte: 'Maior ou igual',
        gt: 'Maior que',
        lte: 'Menor ou igual',
        lt: 'Menor que',
        equals: 'Igual',
        notEquals: 'Diferente',
        is: 'E',
        isNot: 'Nao e',
        before: 'Antes',
        after: 'Depois',
        dateIs: 'Data e',
        dateIsNot: 'Data nao e',
        dateBefore: 'Data antes',
        dateAfter: 'Data depois',
        startsWith: 'Comeca com',
        contains: 'Contem',
        notContains: 'Nao contem',
        endsWith: 'Termina com',
        apply: 'Aplicar',
        matchAny: 'Coincidir qualquer',
        weak: 'Fraca',
        medium: 'Media',
        strong: 'Forte',
        passwordPrompt: 'Digite uma senha',
        fileChosenMessage: 'Arquivo escolhido',
        noFileChosenMessage: 'Nenhum arquivo escolhido',
        chooseYear: 'Escolher ano',
        chooseMonth: 'Escolher mes',
        chooseDate: 'Escolher data',
        prevDecade: 'Decada anterior',
        nextDecade: 'Proxima decada',
        prevYear: 'Ano anterior',
        nextYear: 'Proximo ano',
        prevMonth: 'Mes anterior',
        nextMonth: 'Proximo mes',
        prevHour: 'Hora anterior',
        nextHour: 'Proxima hora',
        prevMinute: 'Minuto anterior',
        nextMinute: 'Proximo minuto',
        prevSecond: 'Segundo anterior',
        nextSecond: 'Proximo segundo',
        am: 'AM',
        pm: 'PM',
        selectionMessage: '{0} itens selecionados',
        aria: {
          trueLabel: 'Verdadeiro',
          falseLabel: 'Falso',
          nullLabel: 'Nao selecionado',
          star: '1 estrela',
          stars: '{star} estrelas',
          selectAll: 'Todos itens selecionados',
          unselectAll: 'Todos itens desmarcados',
          close: 'Fechar',
          previous: 'Anterior',
          next: 'Proximo',
          navigation: 'Navegacao',
          scrollTop: 'Voltar ao topo',
          moveTop: 'Mover para o topo',
          moveUp: 'Mover para cima',
          moveDown: 'Mover para baixo',
          moveBottom: 'Mover para baixo',
          moveToTarget: 'Mover para o destino',
          moveToSource: 'Mover para a origem',
          moveAllToTarget: 'Mover todos para o destino',
          moveAllToSource: 'Mover todos para a origem',
          pageLabel: 'Pagina {page}',
          firstPageLabel: 'Primeira pagina',
          lastPageLabel: 'Ultima pagina',
          nextPageLabel: 'Proxima pagina',
          prevPageLabel: 'Pagina anterior',
          rowsPerPageLabel: 'Itens por pagina',
          previousPageLabel: 'Pagina anterior',
          jumpToPageDropdownLabel: 'Ir para pagina',
          jumpToPageInputLabel: 'Ir para pagina',
          selectRow: 'Linha selecionada',
          unselectRow: 'Linha nao selecionada',
          expandRow: 'Expandir linha',
          collapseRow: 'Recolher linha',
          showFilterMenu: 'Mostrar menu de filtro',
          hideFilterMenu: 'Esconder menu de filtro',
          filterOperator: 'Operador de filtro',
          filterConstraint: 'Restricao de filtro',
          editRow: 'Editar linha',
          saveEdit: 'Salvar edicao',
          cancelEdit: 'Cancelar edicao',
          listView: 'Visao em lista',
          gridView: 'Visao em grade',
          slide: 'Slide',
          slideNumber: 'Numero do slide',
          zoomImage: 'Zoom na imagem',
          zoomIn: 'Aumentar zoom',
          zoomOut: 'Diminuir zoom',
          rotateRight: 'Girar a direita',
          rotateLeft: 'Girar a esquerda',
          listLabel: 'Lista',
          selectColor: 'Selecionar cor',
          removeLabel: 'Remover',
          browseFiles: 'Procurar arquivos',
          maximizeLabel: 'Maximizar',
          minimizeLabel: 'Minimizar',
        },
      },
      theme: {
        preset: Aura,
        options: {
          darkModeSelector: '.app-dark',
          cssLayer: true,
        },
      },
    }),
  ],
};
