export interface FileTreeEntry {
  name: string;
  type: 'file' | 'folder';
  lastCommit: string;
  date: string;
}

export interface TrendingRepo {
  owner: string;
  name: string;
  description: string;
  language: string;
  languageColor: string;
  stars: number;
  forks: number;
  starsToday: number;
  watch: number;
  topics: string[];
  license: string;
  defaultBranch: string;
  fileTree: FileTreeEntry[];
}

export interface TrendingDeveloper {
  rank: number;
  displayName: string;
  username: string;
  popularRepo: {
    name: string;
    description: string;
  };
}

export const TRENDING_REPOS: TrendingRepo[] = [
  {
    owner: 'bytedance',
    name: 'deer-flow',
    description:
      'An open-source long-horizon SuperAgent harness that researches, codes, and creates. With the help of sandboxes, memories, tools, skill, subagents and message gateway, it handles different levels of tasks that could take minutes to hours.',
    language: 'Python',
    languageColor: '#3572A5',
    stars: 72892,
    forks: 9863,
    starsToday: 442,
    watch: 312,
    topics: ['ai', 'agent', 'superagent', 'llm', 'automation', 'python'],
    license: 'Apache-2.0',
    defaultBranch: 'main',
    fileTree: [
      { name: '.github', type: 'folder', lastCommit: 'ci: update workflow', date: '2 weeks ago' },
      { name: 'src', type: 'folder', lastCommit: 'feat: add memory module', date: '3 days ago' },
      { name: 'tests', type: 'folder', lastCommit: 'test: add integration tests', date: '1 week ago' },
      { name: 'docs', type: 'folder', lastCommit: 'docs: update API reference', date: '5 days ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update README', date: '1 week ago' },
      { name: 'pyproject.toml', type: 'file', lastCommit: 'chore: bump version', date: '3 days ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '8 months ago' },
    ],
  },
  {
    owner: 'koala73',
    name: 'worldmonitor',
    description:
      'Real-time global intelligence dashboard. AI-powered news aggregation, geopolitical monitoring, and infrastructure tracking in a unified situational awareness interface',
    language: 'TypeScript',
    languageColor: '#3178C6',
    stars: 58401,
    forks: 9229,
    starsToday: 163,
    watch: 198,
    topics: ['dashboard', 'intelligence', 'monitoring', 'ai', 'real-time'],
    license: 'MIT',
    defaultBranch: 'main',
    fileTree: [
      { name: '.github', type: 'folder', lastCommit: 'ci: add deployment', date: '1 month ago' },
      { name: 'src', type: 'folder', lastCommit: 'feat: add geo tracking', date: '2 days ago' },
      { name: 'public', type: 'folder', lastCommit: 'chore: update assets', date: '2 weeks ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update overview', date: '1 week ago' },
      { name: 'package.json', type: 'file', lastCommit: 'chore: bump deps', date: '2 days ago' },
      { name: 'tsconfig.json', type: 'file', lastCommit: 'chore: update config', date: '1 month ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '1 year ago' },
    ],
  },
  {
    owner: 'penpot',
    name: 'penpot',
    description: 'Penpot: The open-source design tool for design and code collaboration',
    language: 'Clojure',
    languageColor: '#5881D8',
    stars: 52546,
    forks: 3362,
    starsToday: 1135,
    watch: 420,
    topics: ['design', 'open-source', 'figma', 'collaboration', 'svg'],
    license: 'MPL-2.0',
    defaultBranch: 'main',
    fileTree: [
      { name: 'backend', type: 'folder', lastCommit: 'feat: improve performance', date: '1 week ago' },
      { name: 'frontend', type: 'folder', lastCommit: 'fix: resolve rendering issue', date: '3 days ago' },
      { name: 'docker', type: 'folder', lastCommit: 'chore: update Dockerfile', date: '2 weeks ago' },
      { name: 'docs', type: 'folder', lastCommit: 'docs: add deployment guide', date: '1 month ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update README', date: '2 weeks ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '5 years ago' },
    ],
  },
  {
    owner: 'ZhuLinsen',
    name: 'daily_stock_analysis',
    description:
      'LLM-powered multi-market stock analysis system with multi-source market data, real-time news, decision dashboard, automated notifications, and cost-free scheduled runs.',
    language: 'Python',
    languageColor: '#3572A5',
    stars: 45252,
    forks: 41729,
    starsToday: 568,
    watch: 156,
    topics: ['stock', 'llm', 'finance', 'analysis', 'python', 'ai'],
    license: 'MIT',
    defaultBranch: 'main',
    fileTree: [
      { name: 'src', type: 'folder', lastCommit: 'feat: add multi-market support', date: '4 days ago' },
      { name: 'config', type: 'folder', lastCommit: 'chore: update config', date: '1 week ago' },
      { name: 'tests', type: 'folder', lastCommit: 'test: add unit tests', date: '2 weeks ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update README', date: '1 week ago' },
      { name: 'requirements.txt', type: 'file', lastCommit: 'chore: update deps', date: '4 days ago' },
      { name: 'setup.py', type: 'file', lastCommit: 'chore: bump version', date: '1 week ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '6 months ago' },
    ],
  },
  {
    owner: 'microsoft',
    name: 'semantic-kernel',
    description:
      'Integrate cutting-edge LLM technology quickly and easily into your apps with Semantic Kernel',
    language: 'C#',
    languageColor: '#178600',
    stars: 23400,
    forks: 3600,
    starsToday: 312,
    watch: 280,
    topics: ['llm', 'ai', 'microsoft', 'dotnet', 'plugins'],
    license: 'MIT',
    defaultBranch: 'main',
    fileTree: [
      { name: '.github', type: 'folder', lastCommit: 'ci: update pipelines', date: '1 week ago' },
      { name: 'dotnet', type: 'folder', lastCommit: 'feat: add new connector', date: '2 days ago' },
      { name: 'python', type: 'folder', lastCommit: 'fix: resolve import issue', date: '5 days ago' },
      { name: 'samples', type: 'folder', lastCommit: 'docs: add sample app', date: '1 week ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update overview', date: '1 week ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '2 years ago' },
    ],
  },
  {
    owner: 'anthropics',
    name: 'claude-code',
    description:
      'An agentic coding tool that lives in your terminal, understands your codebase, and helps you code faster',
    language: 'TypeScript',
    languageColor: '#3178C6',
    stars: 18200,
    forks: 890,
    starsToday: 520,
    watch: 95,
    topics: ['cli', 'coding', 'ai', 'claude', 'terminal'],
    license: 'MIT',
    defaultBranch: 'main',
    fileTree: [
      { name: 'src', type: 'folder', lastCommit: 'feat: improve code analysis', date: '1 day ago' },
      { name: 'tests', type: 'folder', lastCommit: 'test: add e2e tests', date: '3 days ago' },
      { name: 'docs', type: 'folder', lastCommit: 'docs: update CLI reference', date: '1 week ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update README', date: '3 days ago' },
      { name: 'package.json', type: 'file', lastCommit: 'chore: bump version', date: '1 day ago' },
      { name: 'tsconfig.json', type: 'file', lastCommit: 'chore: update config', date: '2 weeks ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '4 months ago' },
    ],
  },
  {
    owner: 'tursodatabase',
    name: 'turso',
    description: 'Turso is an in-process SQL database, compatible with SQLite.',
    language: 'Rust',
    languageColor: '#DEA584',
    stars: 21025,
    forks: 1074,
    starsToday: 548,
    watch: 88,
    topics: ['database', 'sqlite', 'rust', 'sql', 'embedded'],
    license: 'MIT',
    defaultBranch: 'main',
    fileTree: [
      { name: 'crates', type: 'folder', lastCommit: 'feat: improve query perf', date: '2 days ago' },
      { name: 'libsql', type: 'folder', lastCommit: 'fix: resolve sync issue', date: '5 days ago' },
      { name: 'tests', type: 'folder', lastCommit: 'test: add concurrency tests', date: '1 week ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update README', date: '1 week ago' },
      { name: 'Cargo.toml', type: 'file', lastCommit: 'chore: bump version', date: '2 days ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '3 years ago' },
    ],
  },
  {
    owner: 'openai',
    name: 'codex',
    description: 'Lightweight coding agent that runs in your terminal',
    language: 'TypeScript',
    languageColor: '#3178C6',
    stars: 25800,
    forks: 1900,
    starsToday: 890,
    watch: 145,
    topics: ['cli', 'coding', 'ai', 'openai', 'agent'],
    license: 'Apache-2.0',
    defaultBranch: 'main',
    fileTree: [
      { name: 'src', type: 'folder', lastCommit: 'feat: add tool support', date: '1 day ago' },
      { name: 'tests', type: 'folder', lastCommit: 'test: add integration tests', date: '3 days ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update README', date: '2 days ago' },
      { name: 'package.json', type: 'file', lastCommit: 'chore: bump version', date: '1 day ago' },
      { name: 'tsconfig.json', type: 'file', lastCommit: 'chore: update config', date: '1 week ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '3 months ago' },
    ],
  },
  {
    owner: 'mukul975',
    name: 'Anthropic-Cybersecurity-Skills',
    description:
      '754 structured cybersecurity skills for AI agents. Mapped to 5 frameworks: MITRE ATT&CK, NIST CSF 2.0, MITRE ATLAS, D3FEND & NIST AI RMF.',
    language: 'Python',
    languageColor: '#3572A5',
    stars: 18053,
    forks: 2158,
    starsToday: 361,
    watch: 72,
    topics: ['cybersecurity', 'ai', 'agents', 'mitre', 'skills'],
    license: 'Apache-2.0',
    defaultBranch: 'main',
    fileTree: [
      { name: 'skills', type: 'folder', lastCommit: 'feat: add new skill set', date: '3 days ago' },
      { name: 'frameworks', type: 'folder', lastCommit: 'docs: update mappings', date: '1 week ago' },
      { name: 'tests', type: 'folder', lastCommit: 'test: validate skill formats', date: '2 weeks ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update README', date: '1 week ago' },
      { name: 'pyproject.toml', type: 'file', lastCommit: 'chore: bump version', date: '3 days ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '5 months ago' },
    ],
  },
  {
    owner: 'DeusData',
    name: 'codebase-memory-mcp',
    description:
      'High-performance code intelligence MCP server. Indexes codebases into a persistent knowledge graph - average repo in milliseconds. 158 languages, sub-ms queries, 99% fewer tokens.',
    language: 'C',
    languageColor: '#555555',
    stars: 10846,
    forks: 814,
    starsToday: 1032,
    watch: 64,
    topics: ['mcp', 'code-intelligence', 'knowledge-graph', 'performance'],
    license: 'MIT',
    defaultBranch: 'main',
    fileTree: [
      { name: 'src', type: 'folder', lastCommit: 'feat: add new parser', date: '2 days ago' },
      { name: 'include', type: 'folder', lastCommit: 'fix: resolve memory leak', date: '5 days ago' },
      { name: 'tests', type: 'folder', lastCommit: 'test: add benchmarks', date: '1 week ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update README', date: '1 week ago' },
      { name: 'Makefile', type: 'file', lastCommit: 'chore: optimize build', date: '2 days ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '4 months ago' },
    ],
  },
  {
    owner: 'smicallef',
    name: 'spiderfoot',
    description: 'SpiderFoot automates OSINT for threat intelligence and mapping your attack surface.',
    language: 'Python',
    languageColor: '#3572A5',
    stars: 18912,
    forks: 3117,
    starsToday: 294,
    watch: 112,
    topics: ['osint', 'security', 'threat-intelligence', 'python'],
    license: 'MIT',
    defaultBranch: 'master',
    fileTree: [
      { name: 'spiderfoot', type: 'folder', lastCommit: 'feat: add new module', date: '4 days ago' },
      { name: 'modules', type: 'folder', lastCommit: 'fix: resolve API issue', date: '1 week ago' },
      { name: 'tests', type: 'folder', lastCommit: 'test: add unit tests', date: '2 weeks ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update README', date: '1 week ago' },
      { name: 'requirements.txt', type: 'file', lastCommit: 'chore: update deps', date: '4 days ago' },
      { name: 'setup.py', type: 'file', lastCommit: 'chore: bump version', date: '1 week ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '6 years ago' },
    ],
  },
  {
    owner: 'topoteretes',
    name: 'cognee',
    description:
      'Cognee is the open-source AI memory platform for agents. Give your AI agents persistent long-term memory across sessions with a self-hosted knowledge graph engine.',
    language: 'Python',
    languageColor: '#3572A5',
    stars: 18856,
    forks: 1985,
    starsToday: 347,
    watch: 89,
    topics: ['ai', 'memory', 'knowledge-graph', 'agents', 'rag'],
    license: 'Apache-2.0',
    defaultBranch: 'main',
    fileTree: [
      { name: 'cognee', type: 'folder', lastCommit: 'feat: add graph engine', date: '3 days ago' },
      { name: 'tests', type: 'folder', lastCommit: 'test: add integration tests', date: '1 week ago' },
      { name: 'docs', type: 'folder', lastCommit: 'docs: update API docs', date: '2 weeks ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update README', date: '1 week ago' },
      { name: 'pyproject.toml', type: 'file', lastCommit: 'chore: bump version', date: '3 days ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '1 year ago' },
    ],
  },
  {
    owner: 'palmier-io',
    name: 'palmier-pro',
    description: 'macOS video editor built for AI',
    language: 'Swift',
    languageColor: '#F05138',
    stars: 6263,
    forks: 452,
    starsToday: 1834,
    watch: 45,
    topics: ['macos', 'video', 'editor', 'ai', 'swift'],
    license: 'MIT',
    defaultBranch: 'main',
    fileTree: [
      { name: 'Palmier', type: 'folder', lastCommit: 'feat: add AI features', date: '2 days ago' },
      { name: 'Resources', type: 'folder', lastCommit: 'chore: update assets', date: '1 week ago' },
      { name: 'Tests', type: 'folder', lastCommit: 'test: add UI tests', date: '2 weeks ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update README', date: '1 week ago' },
      { name: 'Package.swift', type: 'file', lastCommit: 'chore: update deps', date: '2 days ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '8 months ago' },
    ],
  },
  {
    owner: 'calesthi',
    name: 'OpenMontage',
    description:
      "World's first open-source, agentic video production system. 12 pipelines, 52 tools, 500+ agent skills.",
    language: 'Python',
    languageColor: '#3572A5',
    stars: 10047,
    forks: 1389,
    starsToday: 987,
    watch: 76,
    topics: ['python', 'agent', 'flux', 'open-source', 'video-production'],
    license: 'AGPL-3.0',
    defaultBranch: 'main',
    fileTree: [
      { name: '.github', type: 'folder', lastCommit: 'ci: update workflow', date: '2 months ago' },
      { name: 'docs', type: 'folder', lastCommit: 'feat(tts): add Doubao provider', date: 'last month' },
      { name: 'lib', type: 'folder', lastCommit: 'fix(source_media_review): use registry.get()', date: '2 months ago' },
      { name: 'pipeline_defs', type: 'folder', lastCommit: 'feat(character-animation): add rigged...', date: '2 months ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update showcase', date: '3 months ago' },
      { name: 'package.json', type: 'file', lastCommit: 'chore: bump dependencies', date: '3 days ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '3 months ago' },
      { name: 'tsconfig.json', type: 'file', lastCommit: 'chore: migrate to TypeScript 6.0', date: '2 months ago' },
    ],
  },
  {
    owner: 'mikumifa',
    name: 'biliTickerBuy',
    description: 'b站会员购购票辅助工具',
    language: 'Python',
    languageColor: '#3572A5',
    stars: 3780,
    forks: 469,
    starsToday: 67,
    watch: 32,
    topics: ['bilibili', 'ticket', 'automation', 'python'],
    license: 'MIT',
    defaultBranch: 'main',
    fileTree: [
      { name: 'src', type: 'folder', lastCommit: 'feat: improve stability', date: '1 week ago' },
      { name: 'config', type: 'folder', lastCommit: 'chore: update config', date: '2 weeks ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update README', date: '1 week ago' },
      { name: 'requirements.txt', type: 'file', lastCommit: 'chore: update deps', date: '1 week ago' },
      { name: 'setup.py', type: 'file', lastCommit: 'chore: bump version', date: '2 weeks ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '1 year ago' },
    ],
  },
  {
    owner: 'oven-sh',
    name: 'bun',
    description: 'Incredibly fast JavaScript runtime, bundler, test runner, and package manager — all in one.',
    language: 'Zig',
    languageColor: '#ec915c',
    stars: 76500,
    forks: 2800,
    starsToday: 145,
    watch: 520,
    topics: ['javascript', 'runtime', 'bundler', 'zig', 'performance'],
    license: 'MIT',
    defaultBranch: 'main',
    fileTree: [
      { name: 'src', type: 'folder', lastCommit: 'feat: improve bundler speed', date: '1 day ago' },
      { name: 'test', type: 'folder', lastCommit: 'test: add Node compat tests', date: '3 days ago' },
      { name: 'packages', type: 'folder', lastCommit: 'chore: update internal deps', date: '1 week ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update README', date: '1 week ago' },
      { name: 'build.zig', type: 'file', lastCommit: 'chore: optimize build', date: '1 day ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '3 years ago' },
    ],
  },
  {
    owner: 'vercel',
    name: 'next.js',
    description: 'The React Framework for the Web.',
    language: 'JavaScript',
    languageColor: '#f1e05a',
    stars: 132000,
    forks: 28500,
    starsToday: 210,
    watch: 1200,
    topics: ['react', 'framework', 'nextjs', 'vercel', 'ssr'],
    license: 'MIT',
    defaultBranch: 'canary',
    fileTree: [
      { name: '.github', type: 'folder', lastCommit: 'ci: update workflows', date: '1 week ago' },
      { name: 'packages', type: 'folder', lastCommit: 'feat: improve streaming', date: '2 days ago' },
      { name: 'examples', type: 'folder', lastCommit: 'docs: add new example', date: '1 week ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update README', date: '1 week ago' },
      { name: 'package.json', type: 'file', lastCommit: 'chore: bump version', date: '2 days ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '7 years ago' },
    ],
  },
  {
    owner: 'denoland',
    name: 'deno',
    description: 'A modern runtime for JavaScript and TypeScript.',
    language: 'Rust',
    languageColor: '#DEA584',
    stars: 101000,
    forks: 5600,
    starsToday: 178,
    watch: 380,
    topics: ['javascript', 'typescript', 'runtime', 'rust', 'secure'],
    license: 'MIT',
    defaultBranch: 'main',
    fileTree: [
      { name: 'cli', type: 'folder', lastCommit: 'feat: improve permissions', date: '2 days ago' },
      { name: 'runtime', type: 'folder', lastCommit: 'fix: resolve memory issue', date: '5 days ago' },
      { name: 'tests', type: 'folder', lastCommit: 'test: add spec tests', date: '1 week ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update README', date: '1 week ago' },
      { name: 'Cargo.toml', type: 'file', lastCommit: 'chore: bump version', date: '2 days ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '6 years ago' },
    ],
  },
  {
    owner: 'langchain-ai',
    name: 'langchain',
    description: 'Build context-aware reasoning applications. LangChain framework for building LLM-powered apps.',
    language: 'Python',
    languageColor: '#3572A5',
    stars: 105000,
    forks: 16900,
    starsToday: 390,
    watch: 890,
    topics: ['llm', 'ai', 'framework', 'python', 'rag', 'agents'],
    license: 'MIT',
    defaultBranch: 'master',
    fileTree: [
      { name: 'libs', type: 'folder', lastCommit: 'feat: add new chain', date: '1 day ago' },
      { name: 'docs', type: 'folder', lastCommit: 'docs: update tutorial', date: '3 days ago' },
      { name: 'tests', type: 'folder', lastCommit: 'test: add unit tests', date: '1 week ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update README', date: '1 week ago' },
      { name: 'pyproject.toml', type: 'file', lastCommit: 'chore: bump version', date: '1 day ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '3 years ago' },
    ],
  },
  {
    owner: 'supabase',
    name: 'supabase',
    description: 'The open source Firebase alternative. Instant APIs, Auth, Realtime, Storage, and Vector Embeddings.',
    language: 'TypeScript',
    languageColor: '#3178C6',
    stars: 77800,
    forks: 7300,
    starsToday: 256,
    watch: 450,
    topics: ['firebase', 'database', 'auth', 'realtime', 'postgres'],
    license: 'Apache-2.0',
    defaultBranch: 'master',
    fileTree: [
      { name: 'apps', type: 'folder', lastCommit: 'feat: add new dashboard', date: '2 days ago' },
      { name: 'packages', type: 'folder', lastCommit: 'fix: resolve auth issue', date: '5 days ago' },
      { name: 'docker', type: 'folder', lastCommit: 'chore: update docker-compose', date: '1 week ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update README', date: '1 week ago' },
      { name: 'package.json', type: 'file', lastCommit: 'chore: bump version', date: '2 days ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '4 years ago' },
    ],
  },
];

export const TRENDING_DEVELOPERS: TrendingDeveloper[] = [
  {
    rank: 1,
    displayName: 'Cole Murray',
    username: 'ColeMurray',
    popularRepo: {
      name: 'background-agents',
      description: 'An open-source background agents coding system',
    },
  },
  {
    rank: 2,
    displayName: 'rUv',
    username: 'ruvnet',
    popularRepo: {
      name: 'RuView',
      description: 'RuView turns commodity WiFi signals into real-time spatial intelligence, vital sign monitoring, and presence detection — all without a camera',
    },
  },
  {
    rank: 3,
    displayName: 'Elie Habib',
    username: 'koala73',
    popularRepo: {
      name: 'worldmonitor',
      description: 'Real-time global intelligence dashboard. AI-powered news aggregation, geopolitical monitoring, and infrastructure tracking in a unified s...',
    },
  },
  {
    rank: 4,
    displayName: 'mumu',
    username: 'ZhuLinsen',
    popularRepo: {
      name: 'daily_stock_analysis',
      description: 'LLM 驱动的多市场股票智能分析系统：多源行情、实时新闻、决策看板与自动推送，支持零成本定时运行。',
    },
  },
  {
    rank: 5,
    displayName: 'Daniel Kraus',
    username: 'dakra',
    popularRepo: {
      name: 'ghostel',
      description: 'Terminal emulator powered by libghostty',
    },
  },
  {
    rank: 6,
    displayName: 'Q00',
    username: 'Q00',
    popularRepo: {
      name: 'ouroboros',
      description: 'Agent OS: Stop prompting. Start specifying.',
    },
  },
  {
    rank: 7,
    displayName: 'Eric Buehler',
    username: 'EricLBuehler',
    popularRepo: {
      name: 'mistral.rs',
      description: 'Fast, flexible LLM inference',
    },
  },
  {
    rank: 8,
    displayName: 'Nik Shevchenko',
    username: 'kodjima33',
    popularRepo: {
      name: 'omi',
      description: 'Open-source AI wearable that records conversations, transcribes them, and extracts insights',
    },
  },
  {
    rank: 9,
    displayName: 'Jarrod Watts',
    username: 'jarrodwatts',
    popularRepo: {
      name: 'claude-hud',
      description: 'A Claude Code plugin that shows what\'s happening - context usage, active tools, running agents, and todo progress',
    },
  },
  {
    rank: 10,
    displayName: 'Clement Tsang',
    username: 'ClementTsang',
    popularRepo: {
      name: 'bottom',
      description: 'Yet another cross-platform graphical process/system monitor.',
    },
  },
  {
    rank: 11,
    displayName: 'Mahesh Sanikommu',
    username: 'MaheshtheDev',
    popularRepo: {
      name: 'supermemory',
      description: 'Supermemory: Your AI memory. Search and remember everything across all your apps.',
    },
  },
  {
    rank: 12,
    displayName: 'Marketcalls',
    username: 'marketcalls',
    popularRepo: {
      name: 'openalgo',
      description: 'Open Source Algo Trading Platform for Everyone',
    },
  },
  {
    rank: 13,
    displayName: 'Raulen Chai',
    username: 'raulenchai',
    popularRepo: {
      name: 'Rapid-MLX',
      description: 'The fastest local AI engine for Apple Silicon. 4.2x faster than Ollama, 0.08s cached TTFT, 100% tool calling, 17 tool parsers, prompt cac...',
    },
  },
  {
    rank: 14,
    displayName: 'xiaolai',
    username: 'xiaolai',
    popularRepo: {
      name: 'too-late',
      description: '《迟到》— 笑来的一部中篇小说（十六年整 生不见人 死不见尸）',
    },
  },
  {
    rank: 15,
    displayName: 'Swyx',
    username: 'swyxio',
    popularRepo: {
      name: 'ai-engineering',
      description: 'A lightweight, fast introduction to AI Engineering for experienced software engineers',
    },
  },
  {
    rank: 16,
    displayName: 'Simon Willison',
    username: 'simonw',
    popularRepo: {
      name: 'datasette',
      description: 'An open source multi-tool for exploring and publishing data',
    },
  },
  {
    rank: 17,
    displayName: 'Theo Browne',
    username: 't3dotgg',
    popularRepo: {
      name: 'ping',
      description: 'Dead simple uptime monitoring. Get notified when your website goes down via Discord, Slack, or email.',
    },
  },
  {
    rank: 18,
    displayName: 'Fireship',
    username: 'fireship-io',
    popularRepo: {
      name: 'bun-hono-turso-demo',
      description: 'Ultrafast fullstack demo with Bun, Hono, and Turso',
    },
  },
  {
    rank: 19,
    displayName: 'Takeshi Iwana',
    username: 'miyakogi',
    popularRepo: {
      name: 'devtool',
      description: 'Open Source AI Coding Agent - runs locally, uses your preferred LLM',
    },
  },
  {
    rank: 20,
    displayName: 'Anil Dash',
    username: 'anildash',
    popularRepo: {
      name: 'social-web-arch',
      description: 'A framework for building social web applications with ActivityPub and AT Protocol support',
    },
  },
];
