export interface FileTreeEntry {
  name: string;
  type: 'file' | 'folder';
  lastCommit: string;
  date: string;
}

export interface TrendingRepo {
  owner: string;
  name: string;
  description: string;
  language: string;
  languageColor: string;
  stars: number;
  forks: number;
  starsToday: number;
  watch: number;
  topics: string[];
  license: string;
  defaultBranch: string;
  fileTree: FileTreeEntry[];
}

export interface TrendingDeveloperRepo {
  name: string;
  description: string;
  language: string;
  languageColor: string;
  stars: number;
  forks: number;
  updated: string;
}

export interface TrendingDeveloperLang {
  name: string;
  color: string;
  percentage: number;
}

export interface TrendingDeveloper {
  rank: number;
  displayName: string;
  username: string;
  bio: string;
  location: string;
  website: string;
  twitter: string;
  avatarColor: string;
  followers: number;
  following: number;
  type?: string;
  topLanguages: TrendingDeveloperLang[];
  pinnedRepos: TrendingDeveloperRepo[];
  repos: TrendingDeveloperRepo[];
  popularRepo: {
    name: string;
    description: string;
  };
}

export const TRENDING_REPOS: TrendingRepo[] = [
  {
    owner: 'bytedance',
    name: 'deer-flow',
    description:
      'An open-source long-horizon SuperAgent harness that researches, codes, and creates. With the help of sandboxes, memories, tools, skill, subagents and message gateway, it handles different levels of tasks that could take minutes to hours.',
    language: 'Python',
    languageColor: '#3572A5',
    stars: 72892,
    forks: 9863,
    starsToday: 442,
    watch: 312,
    topics: ['ai', 'agent', 'superagent', 'llm', 'automation', 'python'],
    license: 'Apache-2.0',
    defaultBranch: 'main',
    fileTree: [
      { name: '.github', type: 'folder', lastCommit: 'ci: update workflow', date: '2 weeks ago' },
      { name: 'src', type: 'folder', lastCommit: 'feat: add memory module', date: '3 days ago' },
      { name: 'tests', type: 'folder', lastCommit: 'test: add integration tests', date: '1 week ago' },
      { name: 'docs', type: 'folder', lastCommit: 'docs: update API reference', date: '5 days ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update README', date: '1 week ago' },
      { name: 'pyproject.toml', type: 'file', lastCommit: 'chore: bump version', date: '3 days ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '8 months ago' },
    ],
  },
  {
    owner: 'koala73',
    name: 'worldmonitor',
    description:
      'Real-time global intelligence dashboard. AI-powered news aggregation, geopolitical monitoring, and infrastructure tracking in a unified situational awareness interface',
    language: 'TypeScript',
    languageColor: '#3178C6',
    stars: 58401,
    forks: 9229,
    starsToday: 163,
    watch: 198,
    topics: ['dashboard', 'intelligence', 'monitoring', 'ai', 'real-time'],
    license: 'MIT',
    defaultBranch: 'main',
    fileTree: [
      { name: '.github', type: 'folder', lastCommit: 'ci: add deployment', date: '1 month ago' },
      { name: 'src', type: 'folder', lastCommit: 'feat: add geo tracking', date: '2 days ago' },
      { name: 'public', type: 'folder', lastCommit: 'chore: update assets', date: '2 weeks ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update overview', date: '1 week ago' },
      { name: 'package.json', type: 'file', lastCommit: 'chore: bump deps', date: '2 days ago' },
      { name: 'tsconfig.json', type: 'file', lastCommit: 'chore: update config', date: '1 month ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '1 year ago' },
    ],
  },
  {
    owner: 'penpot',
    name: 'penpot',
    description: 'Penpot: The open-source design tool for design and code collaboration',
    language: 'Clojure',
    languageColor: '#5881D8',
    stars: 52546,
    forks: 3362,
    starsToday: 1135,
    watch: 420,
    topics: ['design', 'open-source', 'figma', 'collaboration', 'svg'],
    license: 'MPL-2.0',
    defaultBranch: 'main',
    fileTree: [
      { name: 'backend', type: 'folder', lastCommit: 'feat: improve performance', date: '1 week ago' },
      { name: 'frontend', type: 'folder', lastCommit: 'fix: resolve rendering issue', date: '3 days ago' },
      { name: 'docker', type: 'folder', lastCommit: 'chore: update Dockerfile', date: '2 weeks ago' },
      { name: 'docs', type: 'folder', lastCommit: 'docs: add deployment guide', date: '1 month ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update README', date: '2 weeks ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '5 years ago' },
    ],
  },
  {
    owner: 'ZhuLinsen',
    name: 'daily_stock_analysis',
    description:
      'LLM-powered multi-market stock analysis system with multi-source market data, real-time news, decision dashboard, automated notifications, and cost-free scheduled runs.',
    language: 'Python',
    languageColor: '#3572A5',
    stars: 45252,
    forks: 41729,
    starsToday: 568,
    watch: 156,
    topics: ['stock', 'llm', 'finance', 'analysis', 'python', 'ai'],
    license: 'MIT',
    defaultBranch: 'main',
    fileTree: [
      { name: 'src', type: 'folder', lastCommit: 'feat: add multi-market support', date: '4 days ago' },
      { name: 'config', type: 'folder', lastCommit: 'chore: update config', date: '1 week ago' },
      { name: 'tests', type: 'folder', lastCommit: 'test: add unit tests', date: '2 weeks ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update README', date: '1 week ago' },
      { name: 'requirements.txt', type: 'file', lastCommit: 'chore: update deps', date: '4 days ago' },
      { name: 'setup.py', type: 'file', lastCommit: 'chore: bump version', date: '1 week ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '6 months ago' },
    ],
  },
  {
    owner: 'microsoft',
    name: 'semantic-kernel',
    description:
      'Integrate cutting-edge LLM technology quickly and easily into your apps with Semantic Kernel',
    language: 'C#',
    languageColor: '#178600',
    stars: 23400,
    forks: 3600,
    starsToday: 312,
    watch: 280,
    topics: ['llm', 'ai', 'microsoft', 'dotnet', 'plugins'],
    license: 'MIT',
    defaultBranch: 'main',
    fileTree: [
      { name: '.github', type: 'folder', lastCommit: 'ci: update pipelines', date: '1 week ago' },
      { name: 'dotnet', type: 'folder', lastCommit: 'feat: add new connector', date: '2 days ago' },
      { name: 'python', type: 'folder', lastCommit: 'fix: resolve import issue', date: '5 days ago' },
      { name: 'samples', type: 'folder', lastCommit: 'docs: add sample app', date: '1 week ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update overview', date: '1 week ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '2 years ago' },
    ],
  },
  {
    owner: 'anthropics',
    name: 'claude-code',
    description:
      'An agentic coding tool that lives in your terminal, understands your codebase, and helps you code faster',
    language: 'TypeScript',
    languageColor: '#3178C6',
    stars: 18200,
    forks: 890,
    starsToday: 520,
    watch: 95,
    topics: ['cli', 'coding', 'ai', 'claude', 'terminal'],
    license: 'MIT',
    defaultBranch: 'main',
    fileTree: [
      { name: 'src', type: 'folder', lastCommit: 'feat: improve code analysis', date: '1 day ago' },
      { name: 'tests', type: 'folder', lastCommit: 'test: add e2e tests', date: '3 days ago' },
      { name: 'docs', type: 'folder', lastCommit: 'docs: update CLI reference', date: '1 week ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update README', date: '3 days ago' },
      { name: 'package.json', type: 'file', lastCommit: 'chore: bump version', date: '1 day ago' },
      { name: 'tsconfig.json', type: 'file', lastCommit: 'chore: update config', date: '2 weeks ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '4 months ago' },
    ],
  },
  {
    owner: 'tursodatabase',
    name: 'turso',
    description: 'Turso is an in-process SQL database, compatible with SQLite.',
    language: 'Rust',
    languageColor: '#DEA584',
    stars: 21025,
    forks: 1074,
    starsToday: 548,
    watch: 88,
    topics: ['database', 'sqlite', 'rust', 'sql', 'embedded'],
    license: 'MIT',
    defaultBranch: 'main',
    fileTree: [
      { name: 'crates', type: 'folder', lastCommit: 'feat: improve query perf', date: '2 days ago' },
      { name: 'libsql', type: 'folder', lastCommit: 'fix: resolve sync issue', date: '5 days ago' },
      { name: 'tests', type: 'folder', lastCommit: 'test: add concurrency tests', date: '1 week ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update README', date: '1 week ago' },
      { name: 'Cargo.toml', type: 'file', lastCommit: 'chore: bump version', date: '2 days ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '3 years ago' },
    ],
  },
  {
    owner: 'openai',
    name: 'codex',
    description: 'Lightweight coding agent that runs in your terminal',
    language: 'TypeScript',
    languageColor: '#3178C6',
    stars: 25800,
    forks: 1900,
    starsToday: 890,
    watch: 145,
    topics: ['cli', 'coding', 'ai', 'openai', 'agent'],
    license: 'Apache-2.0',
    defaultBranch: 'main',
    fileTree: [
      { name: 'src', type: 'folder', lastCommit: 'feat: add tool support', date: '1 day ago' },
      { name: 'tests', type: 'folder', lastCommit: 'test: add integration tests', date: '3 days ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update README', date: '2 days ago' },
      { name: 'package.json', type: 'file', lastCommit: 'chore: bump version', date: '1 day ago' },
      { name: 'tsconfig.json', type: 'file', lastCommit: 'chore: update config', date: '1 week ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '3 months ago' },
    ],
  },
  {
    owner: 'mukul975',
    name: 'Anthropic-Cybersecurity-Skills',
    description:
      '754 structured cybersecurity skills for AI agents. Mapped to 5 frameworks: MITRE ATT&CK, NIST CSF 2.0, MITRE ATLAS, D3FEND & NIST AI RMF.',
    language: 'Python',
    languageColor: '#3572A5',
    stars: 18053,
    forks: 2158,
    starsToday: 361,
    watch: 72,
    topics: ['cybersecurity', 'ai', 'agents', 'mitre', 'skills'],
    license: 'Apache-2.0',
    defaultBranch: 'main',
    fileTree: [
      { name: 'skills', type: 'folder', lastCommit: 'feat: add new skill set', date: '3 days ago' },
      { name: 'frameworks', type: 'folder', lastCommit: 'docs: update mappings', date: '1 week ago' },
      { name: 'tests', type: 'folder', lastCommit: 'test: validate skill formats', date: '2 weeks ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update README', date: '1 week ago' },
      { name: 'pyproject.toml', type: 'file', lastCommit: 'chore: bump version', date: '3 days ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '5 months ago' },
    ],
  },
  {
    owner: 'DeusData',
    name: 'codebase-memory-mcp',
    description:
      'High-performance code intelligence MCP server. Indexes codebases into a persistent knowledge graph - average repo in milliseconds. 158 languages, sub-ms queries, 99% fewer tokens.',
    language: 'C',
    languageColor: '#555555',
    stars: 10846,
    forks: 814,
    starsToday: 1032,
    watch: 64,
    topics: ['mcp', 'code-intelligence', 'knowledge-graph', 'performance'],
    license: 'MIT',
    defaultBranch: 'main',
    fileTree: [
      { name: 'src', type: 'folder', lastCommit: 'feat: add new parser', date: '2 days ago' },
      { name: 'include', type: 'folder', lastCommit: 'fix: resolve memory leak', date: '5 days ago' },
      { name: 'tests', type: 'folder', lastCommit: 'test: add benchmarks', date: '1 week ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update README', date: '1 week ago' },
      { name: 'Makefile', type: 'file', lastCommit: 'chore: optimize build', date: '2 days ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '4 months ago' },
    ],
  },
  {
    owner: 'smicallef',
    name: 'spiderfoot',
    description: 'SpiderFoot automates OSINT for threat intelligence and mapping your attack surface.',
    language: 'Python',
    languageColor: '#3572A5',
    stars: 18912,
    forks: 3117,
    starsToday: 294,
    watch: 112,
    topics: ['osint', 'security', 'threat-intelligence', 'python'],
    license: 'MIT',
    defaultBranch: 'master',
    fileTree: [
      { name: 'spiderfoot', type: 'folder', lastCommit: 'feat: add new module', date: '4 days ago' },
      { name: 'modules', type: 'folder', lastCommit: 'fix: resolve API issue', date: '1 week ago' },
      { name: 'tests', type: 'folder', lastCommit: 'test: add unit tests', date: '2 weeks ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update README', date: '1 week ago' },
      { name: 'requirements.txt', type: 'file', lastCommit: 'chore: update deps', date: '4 days ago' },
      { name: 'setup.py', type: 'file', lastCommit: 'chore: bump version', date: '1 week ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '6 years ago' },
    ],
  },
  {
    owner: 'topoteretes',
    name: 'cognee',
    description:
      'Cognee is the open-source AI memory platform for agents. Give your AI agents persistent long-term memory across sessions with a self-hosted knowledge graph engine.',
    language: 'Python',
    languageColor: '#3572A5',
    stars: 18856,
    forks: 1985,
    starsToday: 347,
    watch: 89,
    topics: ['ai', 'memory', 'knowledge-graph', 'agents', 'rag'],
    license: 'Apache-2.0',
    defaultBranch: 'main',
    fileTree: [
      { name: 'cognee', type: 'folder', lastCommit: 'feat: add graph engine', date: '3 days ago' },
      { name: 'tests', type: 'folder', lastCommit: 'test: add integration tests', date: '1 week ago' },
      { name: 'docs', type: 'folder', lastCommit: 'docs: update API docs', date: '2 weeks ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update README', date: '1 week ago' },
      { name: 'pyproject.toml', type: 'file', lastCommit: 'chore: bump version', date: '3 days ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '1 year ago' },
    ],
  },
  {
    owner: 'palmier-io',
    name: 'palmier-pro',
    description: 'macOS video editor built for AI',
    language: 'Swift',
    languageColor: '#F05138',
    stars: 6263,
    forks: 452,
    starsToday: 1834,
    watch: 45,
    topics: ['macos', 'video', 'editor', 'ai', 'swift'],
    license: 'MIT',
    defaultBranch: 'main',
    fileTree: [
      { name: 'Palmier', type: 'folder', lastCommit: 'feat: add AI features', date: '2 days ago' },
      { name: 'Resources', type: 'folder', lastCommit: 'chore: update assets', date: '1 week ago' },
      { name: 'Tests', type: 'folder', lastCommit: 'test: add UI tests', date: '2 weeks ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update README', date: '1 week ago' },
      { name: 'Package.swift', type: 'file', lastCommit: 'chore: update deps', date: '2 days ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '8 months ago' },
    ],
  },
  {
    owner: 'calesthi',
    name: 'OpenMontage',
    description:
      "World's first open-source, agentic video production system. 12 pipelines, 52 tools, 500+ agent skills.",
    language: 'Python',
    languageColor: '#3572A5',
    stars: 10047,
    forks: 1389,
    starsToday: 987,
    watch: 76,
    topics: ['python', 'agent', 'flux', 'open-source', 'video-production'],
    license: 'AGPL-3.0',
    defaultBranch: 'main',
    fileTree: [
      { name: '.github', type: 'folder', lastCommit: 'ci: update workflow', date: '2 months ago' },
      { name: 'docs', type: 'folder', lastCommit: 'feat(tts): add Doubao provider', date: 'last month' },
      { name: 'lib', type: 'folder', lastCommit: 'fix(source_media_review): use registry.get()', date: '2 months ago' },
      { name: 'pipeline_defs', type: 'folder', lastCommit: 'feat(character-animation): add rigged...', date: '2 months ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update showcase', date: '3 months ago' },
      { name: 'package.json', type: 'file', lastCommit: 'chore: bump dependencies', date: '3 days ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '3 months ago' },
      { name: 'tsconfig.json', type: 'file', lastCommit: 'chore: migrate to TypeScript 6.0', date: '2 months ago' },
    ],
  },
  {
    owner: 'mikumifa',
    name: 'biliTickerBuy',
    description: 'b站会员购购票辅助工具',
    language: 'Python',
    languageColor: '#3572A5',
    stars: 3780,
    forks: 469,
    starsToday: 67,
    watch: 32,
    topics: ['bilibili', 'ticket', 'automation', 'python'],
    license: 'MIT',
    defaultBranch: 'main',
    fileTree: [
      { name: 'src', type: 'folder', lastCommit: 'feat: improve stability', date: '1 week ago' },
      { name: 'config', type: 'folder', lastCommit: 'chore: update config', date: '2 weeks ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update README', date: '1 week ago' },
      { name: 'requirements.txt', type: 'file', lastCommit: 'chore: update deps', date: '1 week ago' },
      { name: 'setup.py', type: 'file', lastCommit: 'chore: bump version', date: '2 weeks ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '1 year ago' },
    ],
  },
  {
    owner: 'oven-sh',
    name: 'bun',
    description: 'Incredibly fast JavaScript runtime, bundler, test runner, and package manager — all in one.',
    language: 'Zig',
    languageColor: '#ec915c',
    stars: 76500,
    forks: 2800,
    starsToday: 145,
    watch: 520,
    topics: ['javascript', 'runtime', 'bundler', 'zig', 'performance'],
    license: 'MIT',
    defaultBranch: 'main',
    fileTree: [
      { name: 'src', type: 'folder', lastCommit: 'feat: improve bundler speed', date: '1 day ago' },
      { name: 'test', type: 'folder', lastCommit: 'test: add Node compat tests', date: '3 days ago' },
      { name: 'packages', type: 'folder', lastCommit: 'chore: update internal deps', date: '1 week ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update README', date: '1 week ago' },
      { name: 'build.zig', type: 'file', lastCommit: 'chore: optimize build', date: '1 day ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '3 years ago' },
    ],
  },
  {
    owner: 'vercel',
    name: 'next.js',
    description: 'The React Framework for the Web.',
    language: 'JavaScript',
    languageColor: '#f1e05a',
    stars: 132000,
    forks: 28500,
    starsToday: 210,
    watch: 1200,
    topics: ['react', 'framework', 'nextjs', 'vercel', 'ssr'],
    license: 'MIT',
    defaultBranch: 'canary',
    fileTree: [
      { name: '.github', type: 'folder', lastCommit: 'ci: update workflows', date: '1 week ago' },
      { name: 'packages', type: 'folder', lastCommit: 'feat: improve streaming', date: '2 days ago' },
      { name: 'examples', type: 'folder', lastCommit: 'docs: add new example', date: '1 week ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update README', date: '1 week ago' },
      { name: 'package.json', type: 'file', lastCommit: 'chore: bump version', date: '2 days ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '7 years ago' },
    ],
  },
  {
    owner: 'denoland',
    name: 'deno',
    description: 'A modern runtime for JavaScript and TypeScript.',
    language: 'Rust',
    languageColor: '#DEA584',
    stars: 101000,
    forks: 5600,
    starsToday: 178,
    watch: 380,
    topics: ['javascript', 'typescript', 'runtime', 'rust', 'secure'],
    license: 'MIT',
    defaultBranch: 'main',
    fileTree: [
      { name: 'cli', type: 'folder', lastCommit: 'feat: improve permissions', date: '2 days ago' },
      { name: 'runtime', type: 'folder', lastCommit: 'fix: resolve memory issue', date: '5 days ago' },
      { name: 'tests', type: 'folder', lastCommit: 'test: add spec tests', date: '1 week ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update README', date: '1 week ago' },
      { name: 'Cargo.toml', type: 'file', lastCommit: 'chore: bump version', date: '2 days ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '6 years ago' },
    ],
  },
  {
    owner: 'langchain-ai',
    name: 'langchain',
    description: 'Build context-aware reasoning applications. LangChain framework for building LLM-powered apps.',
    language: 'Python',
    languageColor: '#3572A5',
    stars: 105000,
    forks: 16900,
    starsToday: 390,
    watch: 890,
    topics: ['llm', 'ai', 'framework', 'python', 'rag', 'agents'],
    license: 'MIT',
    defaultBranch: 'master',
    fileTree: [
      { name: 'libs', type: 'folder', lastCommit: 'feat: add new chain', date: '1 day ago' },
      { name: 'docs', type: 'folder', lastCommit: 'docs: update tutorial', date: '3 days ago' },
      { name: 'tests', type: 'folder', lastCommit: 'test: add unit tests', date: '1 week ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update README', date: '1 week ago' },
      { name: 'pyproject.toml', type: 'file', lastCommit: 'chore: bump version', date: '1 day ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '3 years ago' },
    ],
  },
  {
    owner: 'supabase',
    name: 'supabase',
    description: 'The open source Firebase alternative. Instant APIs, Auth, Realtime, Storage, and Vector Embeddings.',
    language: 'TypeScript',
    languageColor: '#3178C6',
    stars: 77800,
    forks: 7300,
    starsToday: 256,
    watch: 450,
    topics: ['firebase', 'database', 'auth', 'realtime', 'postgres'],
    license: 'Apache-2.0',
    defaultBranch: 'master',
    fileTree: [
      { name: 'apps', type: 'folder', lastCommit: 'feat: add new dashboard', date: '2 days ago' },
      { name: 'packages', type: 'folder', lastCommit: 'fix: resolve auth issue', date: '5 days ago' },
      { name: 'docker', type: 'folder', lastCommit: 'chore: update docker-compose', date: '1 week ago' },
      { name: 'README.md', type: 'file', lastCommit: 'docs: update README', date: '1 week ago' },
      { name: 'package.json', type: 'file', lastCommit: 'chore: bump version', date: '2 days ago' },
      { name: 'LICENSE', type: 'file', lastCommit: 'Initial commit', date: '4 years ago' },
    ],
  },
];

export const TRENDING_DEVELOPERS: TrendingDeveloper[] = [
  {
    rank: 1,
    displayName: 'Cole Murray',
    username: 'ColeMurray',
    bio: 'Building open-source AI agent systems. Previously @stripe.',
    location: 'San Francisco, CA',
    website: 'https://colemurray.dev',
    twitter: '@cole_murray',
    avatarColor: '#2563eb',
    followers: 12400,
    following: 320,
    topLanguages: [
      { name: 'Python', color: '#3572A5', percentage: 45 },
      { name: 'TypeScript', color: '#3178C6', percentage: 30 },
      { name: 'Rust', color: '#DEA584', percentage: 15 },
      { name: 'Go', color: '#00ADD8', percentage: 10 },
    ],
    pinnedRepos: [
      { name: 'background-agents', description: 'An open-source background agents coding system', language: 'Python', languageColor: '#3572A5', stars: 8200, forks: 1100, updated: '3 days ago' },
      { name: 'agent-protocol', description: 'Standard protocol for building AI agents', language: 'TypeScript', languageColor: '#3178C6', stars: 3400, forks: 420, updated: '1 week ago' },
    ],
    repos: [
      { name: 'background-agents', description: 'An open-source background agents coding system', language: 'Python', languageColor: '#3572A5', stars: 8200, forks: 1100, updated: '3 days ago' },
      { name: 'agent-protocol', description: 'Standard protocol for building AI agents', language: 'TypeScript', languageColor: '#3178C6', stars: 3400, forks: 420, updated: '1 week ago' },
      { name: 'memory-sdk', description: 'Persistent memory SDK for LLM applications', language: 'Python', languageColor: '#3572A5', stars: 1800, forks: 210, updated: '2 weeks ago' },
      { name: 'claude-tools', description: 'Custom tool definitions for Claude', language: 'TypeScript', languageColor: '#3178C6', stars: 920, forks: 85, updated: '3 weeks ago' },
      { name: 'agent-bench', description: 'Benchmarking suite for AI agents', language: 'Python', languageColor: '#3572A5', stars: 640, forks: 72, updated: '1 month ago' },
    ],
    popularRepo: {
      name: 'background-agents',
      description: 'An open-source background agents coding system',
    },
  },
  {
    rank: 2,
    displayName: 'rUv',
    username: 'ruvnet',
    bio: 'Spatial computing researcher. WiFi sensing, vital signs, presence detection.',
    location: 'Tel Aviv, Israel',
    website: 'https://ruv.net',
    twitter: '@ruvnet',
    avatarColor: '#7c3aed',
    followers: 8900,
    following: 180,
    topLanguages: [
      { name: 'Python', color: '#3572A5', percentage: 50 },
      { name: 'JavaScript', color: '#f1e05a', percentage: 25 },
      { name: 'C++', color: '#f34b7d', percentage: 15 },
      { name: 'Shell', color: '#89e051', percentage: 10 },
    ],
    pinnedRepos: [
      { name: 'RuView', description: 'WiFi-based spatial intelligence and vital sign monitoring', language: 'Python', languageColor: '#3572A5', stars: 4500, forks: 620, updated: '5 days ago' },
      { name: 'wifi-sense', description: 'Library for WiFi signal processing and presence detection', language: 'C++', languageColor: '#f34b7d', stars: 1200, forks: 180, updated: '2 weeks ago' },
    ],
    repos: [
      { name: 'RuView', description: 'WiFi-based spatial intelligence and vital sign monitoring', language: 'Python', languageColor: '#3572A5', stars: 4500, forks: 620, updated: '5 days ago' },
      { name: 'wifi-sense', description: 'Library for WiFi signal processing and presence detection', language: 'C++', languageColor: '#f34b7d', stars: 1200, forks: 180, updated: '2 weeks ago' },
      { name: 'spatial-ai', description: 'AI-powered spatial analysis from RF signals', language: 'Python', languageColor: '#3572A5', stars: 780, forks: 95, updated: '3 weeks ago' },
      { name: 'rf-toolkit', description: 'Radio frequency analysis toolkit', language: 'Python', languageColor: '#3572A5', stars: 420, forks: 55, updated: '1 month ago' },
      { name: 'presence-core', description: 'Core presence detection algorithms', language: 'C++', languageColor: '#f34b7d', stars: 310, forks: 40, updated: '1 month ago' },
    ],
    popularRepo: {
      name: 'RuView',
      description: 'WiFi-based spatial intelligence and vital sign monitoring',
    },
  },
  {
    rank: 3,
    displayName: 'Elie Habib',
    username: 'koala73',
    bio: 'Full-stack engineer. Building real-time intelligence dashboards.',
    location: 'Beirut, Lebanon',
    website: 'https://eliehabib.com',
    twitter: '@elie_habib',
    avatarColor: '#059669',
    followers: 6200,
    following: 210,
    topLanguages: [
      { name: 'TypeScript', color: '#3178C6', percentage: 55 },
      { name: 'Go', color: '#00ADD8', percentage: 20 },
      { name: 'Python', color: '#3572A5', percentage: 15 },
      { name: 'Ruby', color: '#701516', percentage: 10 },
    ],
    pinnedRepos: [
      { name: 'worldmonitor', description: 'Real-time global intelligence dashboard', language: 'TypeScript', languageColor: '#3178C6', stars: 58400, forks: 9229, updated: '2 days ago' },
      { name: 'geopolitics-api', description: 'REST API for geopolitical event data', language: 'Go', languageColor: '#00ADD8', stars: 2100, forks: 340, updated: '1 week ago' },
    ],
    repos: [
      { name: 'worldmonitor', description: 'Real-time global intelligence dashboard', language: 'TypeScript', languageColor: '#3178C6', stars: 58400, forks: 9229, updated: '2 days ago' },
      { name: 'geopolitics-api', description: 'REST API for geopolitical event data', language: 'Go', languageColor: '#00ADD8', stars: 2100, forks: 340, updated: '1 week ago' },
      { name: 'news-aggregator', description: 'AI-powered multi-source news aggregation', language: 'Python', languageColor: '#3572A5', stars: 1500, forks: 220, updated: '2 weeks ago' },
      { name: 'infra-monitor', description: 'Infrastructure monitoring and alerting', language: 'Go', languageColor: '#00ADD8', stars: 890, forks: 110, updated: '3 weeks ago' },
      { name: 'dashboard-ui', description: 'Reusable dashboard component library', language: 'TypeScript', languageColor: '#3178C6', stars: 620, forks: 75, updated: '1 month ago' },
    ],
    popularRepo: {
      name: 'worldmonitor',
      description: 'Real-time global intelligence dashboard',
    },
  },
  {
    rank: 4,
    displayName: 'mumu',
    username: 'ZhuLinsen',
    bio: 'Quantitative researcher. LLM-driven stock analysis and financial AI.',
    location: 'Shanghai, China',
    website: 'https://zhu.dev',
    twitter: '@zhu_dev',
    avatarColor: '#dc2626',
    followers: 5800,
    following: 95,
    topLanguages: [
      { name: 'Python', color: '#3572A5', percentage: 70 },
      { name: 'TypeScript', color: '#3178C6', percentage: 15 },
      { name: 'R', color: '#198CE7', percentage: 10 },
      { name: 'Shell', color: '#89e051', percentage: 5 },
    ],
    pinnedRepos: [
      { name: 'daily_stock_analysis', description: 'LLM-driven multi-market stock analysis', language: 'Python', languageColor: '#3572A5', stars: 45252, forks: 41729, updated: '4 days ago' },
      { name: 'quant-lab', description: 'Quantitative trading research framework', language: 'Python', languageColor: '#3572A5', stars: 3200, forks: 480, updated: '1 week ago' },
    ],
    repos: [
      { name: 'daily_stock_analysis', description: 'LLM-driven multi-market stock analysis', language: 'Python', languageColor: '#3572A5', stars: 45252, forks: 41729, updated: '4 days ago' },
      { name: 'quant-lab', description: 'Quantitative trading research framework', language: 'Python', languageColor: '#3572A5', stars: 3200, forks: 480, updated: '1 week ago' },
      { name: 'finance-gpt', description: 'GPT-powered financial document analysis', language: 'Python', languageColor: '#3572A5', stars: 1900, forks: 260, updated: '2 weeks ago' },
      { name: 'market-pulse', description: 'Real-time market data streaming', language: 'Python', languageColor: '#3572A5', stars: 1100, forks: 140, updated: '3 weeks ago' },
      { name: 'backtest-engine', description: 'Event-driven backtesting engine', language: 'Python', languageColor: '#3572A5', stars: 780, forks: 95, updated: '1 month ago' },
    ],
    popularRepo: {
      name: 'daily_stock_analysis',
      description: 'LLM-driven multi-market stock analysis',
    },
  },
  {
    rank: 5,
    displayName: 'Daniel Kraus',
    username: 'dakra',
    bio: 'Systems programmer. Rust enthusiast. Building terminal tools.',
    location: 'Berlin, Germany',
    website: 'https://dakra.dev',
    twitter: '@dakra_dev',
    avatarColor: '#ea580c',
    followers: 4200,
    following: 280,
    topLanguages: [
      { name: 'Rust', color: '#DEA584', percentage: 60 },
      { name: 'Zig', color: '#ec915c', percentage: 20 },
      { name: 'C', color: '#555555', percentage: 15 },
      { name: 'Shell', color: '#89e051', percentage: 5 },
    ],
    pinnedRepos: [
      { name: 'ghostel', description: 'Terminal emulator powered by libghostty', language: 'Rust', languageColor: '#DEA584', stars: 2800, forks: 180, updated: '1 week ago' },
      { name: 'rust-tools', description: 'Collection of CLI utilities in Rust', language: 'Rust', languageColor: '#DEA584', stars: 1400, forks: 120, updated: '2 weeks ago' },
    ],
    repos: [
      { name: 'ghostel', description: 'Terminal emulator powered by libghostty', language: 'Rust', languageColor: '#DEA584', stars: 2800, forks: 180, updated: '1 week ago' },
      { name: 'rust-tools', description: 'Collection of CLI utilities in Rust', language: 'Rust', languageColor: '#DEA584', stars: 1400, forks: 120, updated: '2 weeks ago' },
      { name: 'zig-playground', description: 'Experimental Zig projects and benchmarks', language: 'Zig', languageColor: '#ec915c', stars: 680, forks: 55, updated: '3 weeks ago' },
      { name: 'dotfiles', description: 'Personal development environment', language: 'Shell', languageColor: '#89e051', stars: 420, forks: 85, updated: '1 month ago' },
      { name: 'term-protocol', description: 'Terminal protocol specification', language: 'Rust', languageColor: '#DEA584', stars: 310, forks: 28, updated: '2 months ago' },
    ],
    popularRepo: {
      name: 'ghostel',
      description: 'Terminal emulator powered by libghostty',
    },
  },
  {
    rank: 6,
    displayName: 'Q00',
    username: 'Q00',
    bio: 'Agent OS architect. Specifying intent, not prompts.',
    location: 'Tokyo, Japan',
    website: 'https://q00.dev',
    twitter: '@q00_dev',
    avatarColor: '#0891b2',
    followers: 3800,
    following: 150,
    topLanguages: [
      { name: 'Python', color: '#3572A5', percentage: 40 },
      { name: 'TypeScript', color: '#3178C6', percentage: 30 },
      { name: 'Rust', color: '#DEA584', percentage: 20 },
      { name: 'Go', color: '#00ADD8', percentage: 10 },
    ],
    pinnedRepos: [
      { name: 'ouroboros', description: 'Agent OS: Stop prompting. Start specifying.', language: 'Python', languageColor: '#3572A5', stars: 5600, forks: 780, updated: '2 days ago' },
      { name: 'spec-lang', description: 'Declarative language for agent specifications', language: 'Rust', languageColor: '#DEA584', stars: 1800, forks: 220, updated: '1 week ago' },
    ],
    repos: [
      { name: 'ouroboros', description: 'Agent OS: Stop prompting. Start specifying.', language: 'Python', languageColor: '#3572A5', stars: 5600, forks: 780, updated: '2 days ago' },
      { name: 'spec-lang', description: 'Declarative language for agent specifications', language: 'Rust', languageColor: '#DEA584', stars: 1800, forks: 220, updated: '1 week ago' },
      { name: 'agent-runtime', description: 'Lightweight runtime for agent execution', language: 'Go', languageColor: '#00ADD8', stars: 1200, forks: 150, updated: '2 weeks ago' },
      { name: 'intent-sdk', description: 'SDK for building intent-based applications', language: 'TypeScript', languageColor: '#3178C6', stars: 890, forks: 95, updated: '3 weeks ago' },
      { name: 'agent-bench', description: 'Benchmarking agent performance', language: 'Python', languageColor: '#3572A5', stars: 540, forks: 60, updated: '1 month ago' },
    ],
    popularRepo: {
      name: 'ouroboros',
      description: 'Agent OS: Stop prompting. Start specifying.',
    },
  },
  {
    rank: 7,
    displayName: 'Eric Buehler',
    username: 'EricLBuehler',
    bio: 'ML engineer. Making LLM inference fast and accessible.',
    location: 'Boston, MA',
    website: 'https://ericbuehler.dev',
    twitter: '@ericbuehler',
    avatarColor: '#4f46e5',
    followers: 7200,
    following: 190,
    topLanguages: [
      { name: 'Rust', color: '#DEA584', percentage: 45 },
      { name: 'Python', color: '#3572A5', percentage: 35 },
      { name: 'C++', color: '#f34b7d', percentage: 15 },
      { name: 'CUDA', color: '#3A4E3A', percentage: 5 },
    ],
    pinnedRepos: [
      { name: 'mistral.rs', description: 'Fast, flexible LLM inference', language: 'Rust', languageColor: '#DEA584', stars: 12800, forks: 980, updated: '1 day ago' },
      { name: 'llm-core', description: 'Core library for LLM operations', language: 'Rust', languageColor: '#DEA584', stars: 2400, forks: 310, updated: '1 week ago' },
    ],
    repos: [
      { name: 'mistral.rs', description: 'Fast, flexible LLM inference', language: 'Rust', languageColor: '#DEA584', stars: 12800, forks: 980, updated: '1 day ago' },
      { name: 'llm-core', description: 'Core library for LLM operations', language: 'Rust', languageColor: '#DEA584', stars: 2400, forks: 310, updated: '1 week ago' },
      { name: 'quantize', description: 'Model quantization toolkit', language: 'Python', languageColor: '#3572A5', stars: 1600, forks: 180, updated: '2 weeks ago' },
      { name: 'cuda-kernels', description: 'Optimized CUDA kernels for transformers', language: 'C++', languageColor: '#f34b7d', stars: 980, forks: 120, updated: '3 weeks ago' },
      { name: 'inference-bench', description: 'LLM inference benchmarking suite', language: 'Python', languageColor: '#3572A5', stars: 620, forks: 70, updated: '1 month ago' },
    ],
    popularRepo: {
      name: 'mistral.rs',
      description: 'Fast, flexible LLM inference',
    },
  },
  {
    rank: 8,
    displayName: 'Nik Shevchenko',
    username: 'kodjima33',
    bio: 'Hardware + AI. Building the omi wearable for conversational memory.',
    location: 'Kyiv, Ukraine',
    website: 'https://omi.dev',
    twitter: '@kodjima33',
    avatarColor: '#be185d',
    followers: 5400,
    following: 240,
    topLanguages: [
      { name: 'TypeScript', color: '#3178C6', percentage: 40 },
      { name: 'Python', color: '#3572A5', percentage: 30 },
      { name: 'C', color: '#555555', percentage: 20 },
      { name: 'Swift', color: '#F05138', percentage: 10 },
    ],
    pinnedRepos: [
      { name: 'omi', description: 'Open-source AI wearable for conversational memory', language: 'TypeScript', languageColor: '#3178C6', stars: 15600, forks: 2300, updated: '1 day ago' },
      { name: 'omi-firmware', description: 'Firmware for the omi hardware device', language: 'C', languageColor: '#555555', stars: 1800, forks: 280, updated: '1 week ago' },
    ],
    repos: [
      { name: 'omi', description: 'Open-source AI wearable for conversational memory', language: 'TypeScript', languageColor: '#3178C6', stars: 15600, forks: 2300, updated: '1 day ago' },
      { name: 'omi-firmware', description: 'Firmware for the omi hardware device', language: 'C', languageColor: '#555555', stars: 1800, forks: 280, updated: '1 week ago' },
      { name: 'omi-app', description: 'Mobile app for omi', language: 'Swift', languageColor: '#F05138', stars: 1200, forks: 180, updated: '2 weeks ago' },
      { name: 'transcription-engine', description: 'On-device speech transcription', language: 'Python', languageColor: '#3572A5', stars: 890, forks: 110, updated: '3 weeks ago' },
      { name: 'omi-cloud', description: 'Cloud backend for omi data sync', language: 'TypeScript', languageColor: '#3178C6', stars: 620, forks: 75, updated: '1 month ago' },
    ],
    popularRepo: {
      name: 'omi',
      description: 'Open-source AI wearable for conversational memory',
    },
  },
  {
    rank: 9,
    displayName: 'Jarrod Watts',
    username: 'jarrodwatts',
    bio: 'Developer advocate. Building tools for AI-powered development workflows.',
    location: 'Sydney, Australia',
    website: 'https://jarrodwatts.com',
    twitter: '@jarrodwatts',
    avatarColor: '#16a34a',
    followers: 3200,
    following: 410,
    topLanguages: [
      { name: 'TypeScript', color: '#3178C6', percentage: 50 },
      { name: 'Python', color: '#3572A5', percentage: 25 },
      { name: 'JavaScript', color: '#f1e05a', percentage: 15 },
      { name: 'Shell', color: '#89e051', percentage: 10 },
    ],
    pinnedRepos: [
      { name: 'claude-hud', description: 'Claude Code plugin for monitoring context, tools, and agents', language: 'TypeScript', languageColor: '#3178C6', stars: 4800, forks: 520, updated: '2 days ago' },
      { name: 'ai-devtools', description: 'Collection of AI development utilities', language: 'TypeScript', languageColor: '#3178C6', stars: 1900, forks: 240, updated: '1 week ago' },
    ],
    repos: [
      { name: 'claude-hud', description: 'Claude Code plugin for monitoring context, tools, and agents', language: 'TypeScript', languageColor: '#3178C6', stars: 4800, forks: 520, updated: '2 days ago' },
      { name: 'ai-devtools', description: 'Collection of AI development utilities', language: 'TypeScript', languageColor: '#3178C6', stars: 1900, forks: 240, updated: '1 week ago' },
      { name: 'nextjs-starter', description: 'Production-ready Next.js starter template', language: 'TypeScript', languageColor: '#3178C6', stars: 1100, forks: 180, updated: '2 weeks ago' },
      { name: 'cli-tools', description: 'Handy CLI tools for developers', language: 'Shell', languageColor: '#89e051', stars: 680, forks: 90, updated: '3 weeks ago' },
      { name: 'blog-content', description: 'Source code for my blog and tutorials', language: 'TypeScript', languageColor: '#3178C6', stars: 420, forks: 65, updated: '1 month ago' },
    ],
    popularRepo: {
      name: 'claude-hud',
      description: 'Claude Code plugin for monitoring context, tools, and agents',
    },
  },
  {
    rank: 10,
    displayName: 'Clement Tsang',
    username: 'ClementTsang',
    bio: 'Systems developer. Creating cross-platform monitoring tools.',
    location: 'Vancouver, Canada',
    website: 'https://clementtsang.com',
    twitter: '@clement_tsang',
    avatarColor: '#9333ea',
    followers: 2800,
    following: 160,
    topLanguages: [
      { name: 'Rust', color: '#DEA584', percentage: 55 },
      { name: 'TypeScript', color: '#3178C6', percentage: 20 },
      { name: 'Python', color: '#3572A5', percentage: 15 },
      { name: 'C', color: '#555555', percentage: 10 },
    ],
    pinnedRepos: [
      { name: 'bottom', description: 'Cross-platform graphical process/system monitor', language: 'Rust', languageColor: '#DEA584', stars: 23400, forks: 780, updated: '3 days ago' },
      { name: 'rust-utils', description: 'Useful Rust utilities and macros', language: 'Rust', languageColor: '#DEA584', stars: 890, forks: 95, updated: '2 weeks ago' },
    ],
    repos: [
      { name: 'bottom', description: 'Cross-platform graphical process/system monitor', language: 'Rust', languageColor: '#DEA584', stars: 23400, forks: 780, updated: '3 days ago' },
      { name: 'rust-utils', description: 'Useful Rust utilities and macros', language: 'Rust', languageColor: '#DEA584', stars: 890, forks: 95, updated: '2 weeks ago' },
      { name: 'ts-utils', description: 'TypeScript utility functions', language: 'TypeScript', languageColor: '#3178C6', stars: 420, forks: 55, updated: '3 weeks ago' },
      { name: 'dotfiles', description: 'Personal dev environment config', language: 'Shell', languageColor: '#89e051', stars: 280, forks: 45, updated: '1 month ago' },
      { name: 'benchmarks', description: 'Performance benchmarks for Rust crates', language: 'Rust', languageColor: '#DEA584', stars: 180, forks: 22, updated: '2 months ago' },
    ],
    popularRepo: {
      name: 'bottom',
      description: 'Cross-platform graphical process/system monitor',
    },
  },
  {
    rank: 11,
    displayName: 'Mahesh Sanikommu',
    username: 'MaheshtheDev',
    bio: 'Building AI memory systems. Making machines remember like humans.',
    location: 'Hyderabad, India',
    website: 'https://mahesh.dev',
    twitter: '@mahesh_dev',
    avatarColor: '#ca8a04',
    followers: 4100,
    following: 290,
    topLanguages: [
      { name: 'Python', color: '#3572A5', percentage: 45 },
      { name: 'TypeScript', color: '#3178C6', percentage: 30 },
      { name: 'Rust', color: '#DEA584', percentage: 15 },
      { name: 'Go', color: '#00ADD8', percentage: 10 },
    ],
    pinnedRepos: [
      { name: 'supermemory', description: 'AI memory: search and remember everything across all your apps', language: 'TypeScript', languageColor: '#3178C6', stars: 9800, forks: 1200, updated: '1 day ago' },
      { name: 'memory-engine', description: 'Core engine for semantic memory indexing', language: 'Rust', languageColor: '#DEA584', stars: 2100, forks: 280, updated: '1 week ago' },
    ],
    repos: [
      { name: 'supermemory', description: 'AI memory: search and remember everything across all your apps', language: 'TypeScript', languageColor: '#3178C6', stars: 9800, forks: 1200, updated: '1 day ago' },
      { name: 'memory-engine', description: 'Core engine for semantic memory indexing', language: 'Rust', languageColor: '#DEA584', stars: 2100, forks: 280, updated: '1 week ago' },
      { name: 'rag-toolkit', description: 'RAG pipeline building blocks', language: 'Python', languageColor: '#3572A5', stars: 1400, forks: 180, updated: '2 weeks ago' },
      { name: 'vector-store', description: 'High-performance vector storage', language: 'Rust', languageColor: '#DEA584', stars: 980, forks: 110, updated: '3 weeks ago' },
      { name: 'memory-api', description: 'REST API for memory operations', language: 'Go', languageColor: '#00ADD8', stars: 620, forks: 75, updated: '1 month ago' },
    ],
    popularRepo: {
      name: 'supermemory',
      description: 'AI memory: search and remember everything across all your apps',
    },
  },
  {
    rank: 12,
    displayName: 'Marketcalls',
    username: 'marketcalls',
    bio: 'Algorithmic trading enthusiast. Open-source trading infrastructure for all.',
    location: 'Mumbai, India',
    website: 'https://marketcalls.in',
    twitter: '@marketcalls',
    avatarColor: '#e11d48',
    followers: 3600,
    following: 180,
    topLanguages: [
      { name: 'Python', color: '#3572A5', percentage: 55 },
      { name: 'JavaScript', color: '#f1e05a', percentage: 25 },
      { name: 'Shell', color: '#89e051', percentage: 15 },
      { name: 'SQL', color: '#e38c00', percentage: 5 },
    ],
    pinnedRepos: [
      { name: 'openalgo', description: 'Open source algo trading platform for everyone', language: 'Python', languageColor: '#3572A5', stars: 3200, forks: 580, updated: '3 days ago' },
      { name: 'trading-signals', description: 'Technical analysis signal generators', language: 'Python', languageColor: '#3572A5', stars: 1100, forks: 180, updated: '1 week ago' },
    ],
    repos: [
      { name: 'openalgo', description: 'Open source algo trading platform for everyone', language: 'Python', languageColor: '#3572A5', stars: 3200, forks: 580, updated: '3 days ago' },
      { name: 'trading-signals', description: 'Technical analysis signal generators', language: 'Python', languageColor: '#3572A5', stars: 1100, forks: 180, updated: '1 week ago' },
      { name: 'broker-api', description: 'Unified broker API wrapper', language: 'Python', languageColor: '#3572A5', stars: 780, forks: 120, updated: '2 weeks ago' },
      { name: 'dashboard-trading', description: 'Web-based trading dashboard', language: 'JavaScript', languageColor: '#f1e05a', stars: 520, forks: 85, updated: '3 weeks ago' },
      { name: 'backtest-pro', description: 'Advanced backtesting with realistic fills', language: 'Python', languageColor: '#3572A5', stars: 380, forks: 55, updated: '1 month ago' },
    ],
    popularRepo: {
      name: 'openalgo',
      description: 'Open source algo trading platform for everyone',
    },
  },
  {
    rank: 13,
    displayName: 'Raulen Chai',
    username: 'raulenchai',
    bio: 'Apple Silicon performance optimizer. Making local AI blazing fast.',
    location: 'Kuala Lumpur, Malaysia',
    website: 'https://raulenchai.com',
    twitter: '@raulenchai',
    avatarColor: '#0d9488',
    followers: 2900,
    following: 120,
    topLanguages: [
      { name: 'Swift', color: '#F05138', percentage: 40 },
      { name: 'Python', color: '#3572A5', percentage: 30 },
      { name: 'C++', color: '#f34b7d', percentage: 20 },
      { name: 'Objective-C', color: '#438eff', percentage: 10 },
    ],
    pinnedRepos: [
      { name: 'Rapid-MLX', description: 'Fastest local AI engine for Apple Silicon', language: 'Swift', languageColor: '#F05138', stars: 6400, forks: 780, updated: '2 days ago' },
      { name: 'mlx-inference', description: 'Optimized MLX inference kernels', language: 'C++', languageColor: '#f34b7d', stars: 1800, forks: 220, updated: '1 week ago' },
    ],
    repos: [
      { name: 'Rapid-MLX', description: 'Fastest local AI engine for Apple Silicon', language: 'Swift', languageColor: '#F05138', stars: 6400, forks: 780, updated: '2 days ago' },
      { name: 'mlx-inference', description: 'Optimized MLX inference kernels', language: 'C++', languageColor: '#f34b7d', stars: 1800, forks: 220, updated: '1 week ago' },
      { name: 'swift-ai', description: 'Swift framework for on-device AI', language: 'Swift', languageColor: '#F05138', stars: 1200, forks: 150, updated: '2 weeks ago' },
      { name: 'perf-tools', description: 'Performance profiling tools for Apple Silicon', language: 'Python', languageColor: '#3572A5', stars: 680, forks: 80, updated: '3 weeks ago' },
      { name: 'benchmark-ml', description: 'ML inference benchmark suite', language: 'Python', languageColor: '#3572A5', stars: 420, forks: 55, updated: '1 month ago' },
    ],
    popularRepo: {
      name: 'Rapid-MLX',
      description: 'Fastest local AI engine for Apple Silicon',
    },
  },
  {
    rank: 14,
    displayName: 'xiaolai',
    username: 'xiaolai',
    bio: 'Writer and programmer. Creating tools for personal knowledge management.',
    location: 'Beijing, China',
    website: 'https://xiaolai.me',
    twitter: '@xiaolai',
    avatarColor: '#7c2d12',
    followers: 2400,
    following: 350,
    topLanguages: [
      { name: 'Python', color: '#3572A5', percentage: 40 },
      { name: 'JavaScript', color: '#f1e05a', percentage: 25 },
      { name: 'Markdown', color: '#083fa1', percentage: 20 },
      { name: 'Shell', color: '#89e051', percentage: 15 },
    ],
    pinnedRepos: [
      { name: 'too-late', description: 'A novel about persistence and time', language: 'Markdown', languageColor: '#083fa1', stars: 1800, forks: 320, updated: '1 month ago' },
      { name: 'knowledge-tools', description: 'Tools for personal knowledge management', language: 'Python', languageColor: '#3572A5', stars: 920, forks: 140, updated: '2 weeks ago' },
    ],
    repos: [
      { name: 'too-late', description: 'A novel about persistence and time', language: 'Markdown', languageColor: '#083fa1', stars: 1800, forks: 320, updated: '1 month ago' },
      { name: 'knowledge-tools', description: 'Tools for personal knowledge management', language: 'Python', languageColor: '#3572A5', stars: 920, forks: 140, updated: '2 weeks ago' },
      { name: 'writing-assistant', description: 'AI-powered writing assistant', language: 'Python', languageColor: '#3572A5', stars: 680, forks: 95, updated: '3 weeks ago' },
      { name: 'blog-engine', description: 'Minimal static blog generator', language: 'JavaScript', languageColor: '#f1e05a', stars: 420, forks: 65, updated: '1 month ago' },
      { name: 'dotfiles', description: 'Development environment setup', language: 'Shell', languageColor: '#89e051', stars: 280, forks: 50, updated: '2 months ago' },
    ],
    popularRepo: {
      name: 'too-late',
      description: 'A novel about persistence and time',
    },
  },
  {
    rank: 15,
    displayName: 'Swyx',
    username: 'swyxio',
    bio: 'AI Engineer. Writer. Speaker. Co-founder @latent.space. Author of AI Engineering.',
    location: 'Singapore',
    website: 'https://swyx.io',
    twitter: '@swyx',
    avatarColor: '#2563eb',
    followers: 18200,
    following: 890,
    topLanguages: [
      { name: 'TypeScript', color: '#3178C6', percentage: 45 },
      { name: 'Python', color: '#3572A5', percentage: 30 },
      { name: 'JavaScript', color: '#f1e05a', percentage: 15 },
      { name: 'Markdown', color: '#083fa1', percentage: 10 },
    ],
    pinnedRepos: [
      { name: 'ai-engineering', description: 'Lightweight intro to AI Engineering for experienced software engineers', language: 'TypeScript', languageColor: '#3178C6', stars: 8400, forks: 1100, updated: '3 days ago' },
      { name: 'latent-space', description: 'Source code for the latent.space blog and community', language: 'TypeScript', languageColor: '#3178C6', stars: 3200, forks: 480, updated: '1 week ago' },
    ],
    repos: [
      { name: 'ai-engineering', description: 'Lightweight intro to AI Engineering for experienced software engineers', language: 'TypeScript', languageColor: '#3178C6', stars: 8400, forks: 1100, updated: '3 days ago' },
      { name: 'latent-space', description: 'Source code for the latent.space blog and community', language: 'TypeScript', languageColor: '#3178C6', stars: 3200, forks: 480, updated: '1 week ago' },
      { name: 'llm-workshop', description: 'Workshop materials for LLM application development', language: 'Python', languageColor: '#3572A5', stars: 1900, forks: 320, updated: '2 weeks ago' },
      { name: 'prompt-engineering', description: 'Prompt engineering guide and examples', language: 'Python', languageColor: '#3572A5', stars: 1200, forks: 180, updated: '3 weeks ago' },
      { name: 'talks', description: 'Slides and code from conference talks', language: 'TypeScript', languageColor: '#3178C6', stars: 680, forks: 95, updated: '1 month ago' },
    ],
    popularRepo: {
      name: 'ai-engineering',
      description: 'Lightweight intro to AI Engineering for experienced software engineers',
    },
  },
  {
    rank: 16,
    displayName: 'Simon Willison',
    username: 'simonw',
    bio: 'Creator of Datasette and LLM. Writing about Python, data journalism, and AI tools at simonwillison.net.',
    location: 'London, UK',
    website: 'https://simonwillison.net',
    twitter: '@simonw',
    avatarColor: '#1d4ed8',
    followers: 24500,
    following: 1200,
    topLanguages: [
      { name: 'Python', color: '#3572A5', percentage: 60 },
      { name: 'JavaScript', color: '#f1e05a', percentage: 20 },
      { name: 'CSS', color: '#563d7c', percentage: 10 },
      { name: 'Shell', color: '#89e051', percentage: 10 },
    ],
    pinnedRepos: [
      { name: 'datasette', description: 'Open source multi-tool for exploring and publishing data', language: 'Python', languageColor: '#3572A5', stars: 9200, forks: 680, updated: '2 days ago' },
      { name: 'llm', description: 'CLI tool and Python library for interacting with LLMs', language: 'Python', languageColor: '#3572A5', stars: 7800, forks: 520, updated: '1 day ago' },
    ],
    repos: [
      { name: 'datasette', description: 'Open source multi-tool for exploring and publishing data', language: 'Python', languageColor: '#3572A5', stars: 9200, forks: 680, updated: '2 days ago' },
      { name: 'llm', description: 'CLI tool and Python library for interacting with LLMs', language: 'Python', languageColor: '#3572A5', stars: 7800, forks: 520, updated: '1 day ago' },
      { name: 'datasette-template', description: 'Template plugin for Datasette', language: 'Python', languageColor: '#3572A5', stars: 1400, forks: 180, updated: '1 week ago' },
      { name: 'sqlite-utils', description: 'Python CLI and library for manipulating SQLite databases', language: 'Python', languageColor: '#3572A5', stars: 1200, forks: 150, updated: '2 weeks ago' },
      { name: 'til', description: 'Today I Learned — a collection of short writeups', language: 'Markdown', languageColor: '#083fa1', stars: 980, forks: 220, updated: '3 weeks ago' },
    ],
    popularRepo: {
      name: 'datasette',
      description: 'Open source multi-tool for exploring and publishing data',
    },
  },
  {
    rank: 17,
    displayName: 'Theo Browne',
    username: 't3dotgg',
    bio: 'CEO @ Ping. Previously @ Vercel. Building tools for the modern web. TypeScript maximalist.',
    location: 'San Jose, CA',
    website: 'https://theo.dev',
    twitter: '@t3dotgg',
    avatarColor: '#0284c7',
    followers: 15800,
    following: 620,
    topLanguages: [
      { name: 'TypeScript', color: '#3178C6', percentage: 55 },
      { name: 'Rust', color: '#DEA584', percentage: 20 },
      { name: 'Go', color: '#00ADD8', percentage: 15 },
      { name: 'Python', color: '#3572A5', percentage: 10 },
    ],
    pinnedRepos: [
      { name: 'ping', description: 'Dead simple uptime monitoring', language: 'TypeScript', languageColor: '#3178C6', stars: 3400, forks: 420, updated: '2 days ago' },
      { name: 'create-t3-turbo', description: 'T3 Stack monorepo template', language: 'TypeScript', languageColor: '#3178C6', stars: 6200, forks: 890, updated: '1 week ago' },
    ],
    repos: [
      { name: 'ping', description: 'Dead simple uptime monitoring', language: 'TypeScript', languageColor: '#3178C6', stars: 3400, forks: 420, updated: '2 days ago' },
      { name: 'create-t3-turbo', description: 'T3 Stack monorepo template', language: 'TypeScript', languageColor: '#3178C6', stars: 6200, forks: 890, updated: '1 week ago' },
      { name: 'youtube-dl', description: 'YouTube video downloader CLI', language: 'Rust', languageColor: '#DEA584', stars: 2100, forks: 280, updated: '2 weeks ago' },
      { name: 't3-stack', description: 'The T3 Stack for modern web apps', language: 'TypeScript', languageColor: '#3178C6', stars: 1800, forks: 240, updated: '3 weeks ago' },
      { name: 'config', description: 'Personal tooling configuration', language: 'TypeScript', languageColor: '#3178C6', stars: 580, forks: 90, updated: '1 month ago' },
    ],
    popularRepo: {
      name: 'ping',
      description: 'Dead simple uptime monitoring',
    },
  },
  {
    rank: 18,
    displayName: 'Fireship',
    username: 'fireship-io',
    bio: 'Developer content creator. 100 seconds of code. CEO @ Fireship.',
    location: 'Colorado, USA',
    website: 'https://fireship.io',
    twitter: '@firabord',
    avatarColor: '#ea580c',
    followers: 28000,
    following: 420,
    topLanguages: [
      { name: 'TypeScript', color: '#3178C6', percentage: 40 },
      { name: 'Dart', color: '#00B4AB', percentage: 20 },
      { name: 'Python', color: '#3572A5', percentage: 20 },
      { name: 'Rust', color: '#DEA584', percentage: 20 },
    ],
    pinnedRepos: [
      { name: 'bun-hono-turso-demo', description: 'Ultrafast fullstack demo with Bun, Hono, and Turso', language: 'TypeScript', languageColor: '#3178C6', stars: 1200, forks: 180, updated: '1 week ago' },
      { name: 'supabase-stripe-starter', description: 'Fullstack starter with Supabase and Stripe', language: 'TypeScript', languageColor: '#3178C6', stars: 2400, forks: 380, updated: '2 weeks ago' },
    ],
    repos: [
      { name: 'bun-hono-turso-demo', description: 'Ultrafast fullstack demo with Bun, Hono, and Turso', language: 'TypeScript', languageColor: '#3178C6', stars: 1200, forks: 180, updated: '1 week ago' },
      { name: 'supabase-stripe-starter', description: 'Fullstack starter with Supabase and Stripe', language: 'TypeScript', languageColor: '#3178C6', stars: 2400, forks: 380, updated: '2 weeks ago' },
      { name: 'flutter-starter', description: 'Flutter project template with auth and database', language: 'Dart', languageColor: '#00B4AB', stars: 1800, forks: 290, updated: '3 weeks ago' },
      { name: 'ai-hello-world', description: 'Hello world in every AI framework', language: 'Python', languageColor: '#3572A5', stars: 1400, forks: 200, updated: '1 month ago' },
      { name: 'content', description: 'Source code for Fireship video content', language: 'TypeScript', languageColor: '#3178C6', stars: 980, forks: 150, updated: '1 month ago' },
    ],
    popularRepo: {
      name: 'bun-hono-turso-demo',
      description: 'Ultrafast fullstack demo with Bun, Hono, and Turso',
    },
  },
  {
    rank: 19,
    displayName: 'Takeshi Iwana',
    username: 'miyakogi',
    bio: 'AI coding agent developer. Open source advocate. Runs locally.',
    location: 'Osaka, Japan',
    website: 'https://miyakogi.dev',
    twitter: '@miyakogi_dev',
    avatarColor: '#4338ca',
    followers: 2100,
    following: 280,
    topLanguages: [
      { name: 'Python', color: '#3572A5', percentage: 50 },
      { name: 'TypeScript', color: '#3178C6', percentage: 25 },
      { name: 'Rust', color: '#DEA584', percentage: 15 },
      { name: 'Go', color: '#00ADD8', percentage: 10 },
    ],
    pinnedRepos: [
      { name: 'devtool', description: 'Open Source AI Coding Agent - runs locally', language: 'Python', languageColor: '#3572A5', stars: 4200, forks: 580, updated: '2 days ago' },
      { name: 'local-llm', description: 'Local LLM integration toolkit', language: 'Rust', languageColor: '#DEA584', stars: 1800, forks: 220, updated: '1 week ago' },
    ],
    repos: [
      { name: 'devtool', description: 'Open Source AI Coding Agent - runs locally', language: 'Python', languageColor: '#3572A5', stars: 4200, forks: 580, updated: '2 days ago' },
      { name: 'local-llm', description: 'Local LLM integration toolkit', language: 'Rust', languageColor: '#DEA584', stars: 1800, forks: 220, updated: '1 week ago' },
      { name: 'code-index', description: 'Fast code indexing for AI agents', language: 'Python', languageColor: '#3572A5', stars: 980, forks: 120, updated: '2 weeks ago' },
      { name: 'agent-plugins', description: 'Plugin system for AI coding agents', language: 'TypeScript', languageColor: '#3178C6', stars: 680, forks: 85, updated: '3 weeks ago' },
      { name: 'terminal-ui', description: 'Terminal UI components for dev tools', language: 'Go', languageColor: '#00ADD8', stars: 420, forks: 55, updated: '1 month ago' },
    ],
    popularRepo: {
      name: 'devtool',
      description: 'Open Source AI Coding Agent - runs locally',
    },
  },
  {
    rank: 20,
    displayName: 'Anil Dash',
    username: 'anildash',
    bio: 'CEO @ Glitch. Advocate for the open web. Writing about tech, culture, and policy.',
    location: 'New York, NY',
    website: 'https://anildash.com',
    twitter: '@anildash',
    avatarColor: '#be123c',
    followers: 12800,
    following: 1500,
    topLanguages: [
      { name: 'JavaScript', color: '#f1e05a', percentage: 35 },
      { name: 'Ruby', color: '#701516', percentage: 25 },
      { name: 'Python', color: '#3572A5', percentage: 20 },
      { name: 'HTML', color: '#e34c26', percentage: 20 },
    ],
    pinnedRepos: [
      { name: 'social-web-arch', description: 'Framework for social web apps with ActivityPub and AT Protocol', language: 'JavaScript', languageColor: '#f1e05a', stars: 2800, forks: 380, updated: '1 week ago' },
      { name: 'open-web-tools', description: 'Tools for building on the open web', language: 'Ruby', languageColor: '#701516', stars: 1200, forks: 180, updated: '2 weeks ago' },
    ],
    repos: [
      { name: 'social-web-arch', description: 'Framework for social web apps with ActivityPub and AT Protocol', language: 'JavaScript', languageColor: '#f1e05a', stars: 2800, forks: 380, updated: '1 week ago' },
      { name: 'open-web-tools', description: 'Tools for building on the open web', language: 'Ruby', languageColor: '#701516', stars: 1200, forks: 180, updated: '2 weeks ago' },
      { name: 'microblog', description: 'Minimal blogging platform', language: 'Ruby', languageColor: '#701516', stars: 890, forks: 140, updated: '3 weeks ago' },
      { name: 'web-indie', description: 'Indie web publishing toolkit', language: 'JavaScript', languageColor: '#f1e05a', stars: 620, forks: 95, updated: '1 month ago' },
      { name: 'policy-tech', description: 'Tech policy analysis tools', language: 'Python', languageColor: '#3572A5', stars: 480, forks: 70, updated: '2 months ago' },
    ],
    popularRepo: {
      name: 'social-web-arch',
      description: 'Framework for social web apps with ActivityPub and AT Protocol',
    },
  },
];
